language: node_js
node_js:
  - 10
  - 8


before_install:
  - npm install -g typescript@3.3.4000
  - npm install codecov -g
  - npm install nyc -g

script:
  - tsc
  - nyc npm test

after_success:
  - codecov
