language: node_js
node_js:
  - 10
  - 8


before_install:
  - npm install -g typescript@3.3.4000
  - npm install nyc -g

script:
  - tsc
  - nyc npm test

after_success:
  - nyc report --reporter=json
  - bash <(curl -s https://codecov.io/bash)
