language: node_js
node_js:
  - 10

cache:
  directories:
    - node_modules

before_install:
  - npm install typescript@3.3.4000
  - npm install nyc@13.3.0

script:
  - tsc
  - nyc npm test

after_success:
  - nyc report --reporter=json
  - bash <(curl -s https://codecov.io/bash)
