language: node_js
node_js:
  - 10

cache:
  directories:
    - $HOME/.npm

install:
  - npm install typescript@3.9.4000
  - npm install nyc@13.3.0
  - npm install tslint

script:
  - tsc
  - tslint ./src/**/*.ts --format verbose
  - nyc npm test

after_success:
  - nyc report --reporter=json
  - bash <(curl -s https://codecov.io/bash)
